### ISSUE TITLE
Dual logicvc/screen configuration issue.

### ISSUE THREAD

**Issue by D953i** [logicbricks/linux-xlnx-xylon#2]
I'm trying to get dual screen configuration working and have a issue with it, which I suspect is driver related.

So, I got a hardware design(Vivado 2014.4) with two logicvc-3.01.a IP blocks and two LCD screens( first - 5" 800x480 and second - 8.4" 800x600).

If I enable(uncommenting description in DTS) either one of them - I got /dev/fb0 device and everything works as expected (correct resolution and timing settings). For testing I'm using Qt5 example app and ts_calibrate utility. Both tests generate image on a corresponding screen.

But If I enable  both of them at the same time:
1. Both /dev/fb0 and /dev/fb1 got created, but...
2. Qt test app and ts_calibrate show image on screen1 if I specify /dev/fb0 and no image if I specify /dev/fb1.
3. cat /sys/class/graphics/fb0/name gives me: Xylon FB0
4. cat /sys/class/graphics/fb1/name also gives me: Xylon FB0
5. cat /sys/class/graphics/fb0/mode    : U:800x480p-77  which is correct.
6. cat /sys/class/graphics/fb1/mode    : U:800x600p-67 which is correct.

Any ideas?

Portion of my DTS:

		logicvc_0: logicvc@43c00000 {
			compatible = "xylon,logicvc-4.00.a";
			interrupt-parent = <&intc>;
			interrupts = <0 29 4>;
			reg = <0x43c00000 0x10000>;
			readable-regs;
			size-position;
			pixel-stride = <1024>;
			power-delay = <0>;
			signal-delay = <0>;
			layer_0 {
				address = <0x3C000000>;
				buffer-offset = <4096>;
				bits-per-pixel = <32>;
				type = "rgb";
				transparency = "layer";
			};
			display-timings {
				native-mode = <&nhd5>;
				nhd5: 800x480 {
					clock-frequency = <40000000>;
					hactive = <800>;
					vactive = <480>;
					hfront-porch = <40>;
					hback-porch = <88>;
					hsync-len = <48>;
					vfront-porch = <13>;
					vback-porch = <32>;
					vsync-len = <5>;
				};
			};
		};

		logicvc_1: logicvc@43c10000 {
			compatible = "xylon,logicvc-4.00.a";
			interrupt-parent = <&intc>;
			interrupts = <0 32 4>;
			reg = <0x43c10000 0x10000>;
			readable-regs;
			size-position;
			pixel-stride = <1024>;
			power-delay = <0>;
			signal-delay = <0>;
			layer_0 {
				address = <0x38000000>;
				buffer-offset = <4096>;
				bits-per-pixel = <32>;
				type = "rgb";
				transparency = "layer";
			};
			display-timings {
				native-mode = <&lq084>;
				lq084: 800x600 {
					clock-frequency = <40000000>;
					hactive = <800>;
					vactive = <600>;
					hfront-porch = <40>;
					hback-porch = <40>;
					hsync-len = <48>;
					vfront-porch = <29>;
					vback-porch = <13>;
					vsync-len = <3>;
				};
			};
		};

		xylon_fb0 {
			compatible = "xylon,fb-3.00.a";
			device = <&logicvc_0>;
			console-layer = <0>;
			edid-print;
			vsync-irq;
		};

		xylon_fb1 {
			compatible = "xylon,fb-3.00.a";
			device = <&logicvc_1>;
			console-layer = <0>;
			edid-print;
			vsync-irq;
		};

Related portion of the boot log:

[    1.844142] logicvc amba_pl:xylon_fb0: logiCVC IP core 3.01.a
[    1.844161] logicvc amba_pl:xylon_fb0: external pixel clock
[    1.854052] Console: switching to colour frame buffer device 100x30
[    1.862369] logicvc amba_pl:xylon_fb1: logiCVC IP core 3.01.a
[    1.862388] logicvc amba_pl:xylon_fb1: external pixel clock

**Comment by D953i** [comment]
A few more details on dual logicvc configuration. Again, /dev/fb0 works and /dev/fb1 have no image.

Today I connected oscilloscope to our LVDS-to-TFT LCD adapter for second screen and I can see that when I start test application (on /dev/fb1) I can see clock, but no data signals. 

Again, my hardware seems to be fine. I did swap them physically and thru DTS (made /dev/fb1 to appear as /dev/fb0 and wise versa) and both adapter+screen work as /dev/fb0 device in dual configuration.

DTS nodes seems to be fine too. I verified them by commenting out one of the logicvc+fb node and leaving other intact. As a result I get perfectly working /dev/fb0 with correct resolution and timings.

**Comment by logicbricks** [comment]
Question, logicvc_0 on /dev/fb0 displays image, and logicvc_1on /dev/fb1 does not?
Try to turn on logiCVC 1 manually from console by writing "1" directly to layer 0 control register (offset 0x138) and and check have control signals appear.

**Comment by D953i** [comment]
Just to verify I'm doing what you asked: I'm using devmem to write/read to address from console.

 devmem 0x43c00138 32 1, change nothing. 
And I tried it both with and without test app running on /dev/fb1

**Comment by logicbricks** [comment]
I would need registers dump of both logicvc devices after startup.
Offsets are from 0x00 to 0x78 and from 0x100 to 0x140 with 8 bytes reg distance (0x00, 0x08, 0x10, 0x18...)
Then I will send you few more manual steps to tryout.

**Comment by D953i** [comment]
Ok, right now in dual configuration:
 logicvc IP on 0x43c1_0000 set as /dev/fb0 - shows image.
 logicvc IP on 0x43c0_0000 set as /dev/fb1 - no image.



/dev/fb0: 0x43c10000 = 0x00000027.
/dev/fb0: 0x43c10008 = 0x0000002f.
/dev/fb0: 0x43c10010 = 0x00000027.
/dev/fb0: 0x43c10018 = 0x0000031f.
/dev/fb0: 0x43c10020 = 0x0000001c.
/dev/fb0: 0x43c10028 = 0x00000002.
/dev/fb0: 0x43c10030 = 0x0000000c.
/dev/fb0: 0x43c10038 = 0x00000257.
/dev/fb0: 0x43c10040 = 0x00000015.
/dev/fb0: 0x43c10048 = 0x00000000.
/dev/fb0: 0x43c10050 = 0x00000000.
/dev/fb0: 0x43c10058 = 0x00000000.
/dev/fb0: 0x43c10060 = 0x00000000.
/dev/fb0: 0x43c10068 = 0x00000000.
/dev/fb0: 0x43c10070 = 0x0000ffdf.
/dev/fb0: 0x43c10078 = 0x0000000b.



/dev/fb1: 0x43c00000 = 0x0000007f.
/dev/fb1: 0x43c00008 = 0x0000007f.
/dev/fb1: 0x43c00010 = 0x0000007f.
/dev/fb1: 0x43c00018 = 0x0000027f.
/dev/fb1: 0x43c00020 = 0x00000000.
/dev/fb1: 0x43c00028 = 0x00000000.
/dev/fb1: 0x43c00030 = 0x00000000.
/dev/fb1: 0x43c00038 = 0x000001df.
/dev/fb1: 0x43c00040 = 0x00000000.
/dev/fb1: 0x43c00048 = 0x00000000.
/dev/fb1: 0x43c00050 = 0x00000000.
/dev/fb1: 0x43c00058 = 0x00000000.
/dev/fb1: 0x43c00060 = 0x00000000.
/dev/fb1: 0x43c00068 = 0x00000000.
/dev/fb1: 0x43c00070 = 0x0000ffdf.
/dev/fb1: 0x43c00078 = 0x00000000.

**Comment by D953i** [comment]
Right now in a dual configuration:
logicvc on 0x43c1_0000 configured as /dev/fb0 - shows image.
logicvc on 0x43c0_0000 configured as /dev/fb1 - no image.

/dev/fb0: 0x43c10000 = 0x00000027.
/dev/fb0: 0x43c10008 = 0x0000002f.
/dev/fb0: 0x43c10010 = 0x00000027.
/dev/fb0: 0x43c10018 = 0x0000031f.
/dev/fb0: 0x43c10020 = 0x0000001c.
/dev/fb0: 0x43c10028 = 0x00000002.
/dev/fb0: 0x43c10030 = 0x0000000c.
/dev/fb0: 0x43c10038 = 0x00000257.
/dev/fb0: 0x43c10040 = 0x00000015.
/dev/fb0: 0x43c10048 = 0x00000000.
/dev/fb0: 0x43c10050 = 0x00000000.
/dev/fb0: 0x43c10058 = 0x00000000.
/dev/fb0: 0x43c10060 = 0x00000000.
/dev/fb0: 0x43c10068 = 0x00000000.
/dev/fb0: 0x43c10070 = 0x0000ffdf.
/dev/fb0: 0x43c10078 = 0x0000000b.
/dev/fb0: 0x43c10100 = 0x00000000.
/dev/fb0: 0x43c10108 = 0x00000000.
/dev/fb0: 0x43c10110 = 0x0000031f.
/dev/fb0: 0x43c10118 = 0x00000257.
/dev/fb0: 0x43c10120 = 0x0000031f.
/dev/fb0: 0x43c10128 = 0x00000257.
/dev/fb0: 0x43c10130 = 0x00000000.
/dev/fb0: 0x43c10138 = 0x00000003.

/dev/fb1: 0x43c00000 = 0x0000007f.
/dev/fb1: 0x43c00008 = 0x0000007f.
/dev/fb1: 0x43c00010 = 0x0000007f.
/dev/fb1: 0x43c00018 = 0x0000027f.
/dev/fb1: 0x43c00020 = 0x00000000.
/dev/fb1: 0x43c00028 = 0x00000000.
/dev/fb1: 0x43c00030 = 0x00000000.
/dev/fb1: 0x43c00038 = 0x000001df.
/dev/fb1: 0x43c00040 = 0x00000000.
/dev/fb1: 0x43c00048 = 0x00000000.
/dev/fb1: 0x43c00050 = 0x00000000.
/dev/fb1: 0x43c00058 = 0x00000000.
/dev/fb1: 0x43c00060 = 0x00000000.
/dev/fb1: 0x43c00068 = 0x00000000.
/dev/fb1: 0x43c00070 = 0x0000ffdf.
/dev/fb1: 0x43c00078 = 0x00000000.
/dev/fb1: 0x43c00100 = 0x00000000.
/dev/fb1: 0x43c00108 = 0x00000000.
/dev/fb1: 0x43c00110 = 0x0000027f.
/dev/fb1: 0x43c00118 = 0x000001df.
/dev/fb1: 0x43c00120 = 0x0000027f.
/dev/fb1: 0x43c00128 = 0x000001df.
/dev/fb1: 0x43c00130 = 0x00000000.
/dev/fb1: 0x43c00138 = 0x00000002.

**Comment by logicbricks** [comment]
logicvc_1 is not initialized at all. That is the reason why device is not working.
Why is not initialized is another question.
Enable the driver debug logs in file "xylonfb_core.h" by replacing #define DEBUG_LEVEL CORE with #define DEBUG_LEVEL INFO and add below #define DEBUG.

Important, please send all future messages related to SW or HW issues with any attachments to "support@logicbricks.com", including the one with above mentioned logs.
There you will get official support.
